package `in`.hypernation.payup.ui.theme

import androidx.compose.ui.graphics.Color

val Purple = Color(0xFF702AE2)
val Purple40 = Color(0xFF6D49A9) // Secondary Gradient Color

val Pink80 = Color(0xFFEFB8C8)
val Peach = Color(0xFFF5B041)

val GhostBlack = Color(0xFF1E1E1E)
val GhostBlack60 = Color(0x991E1E1E)
val GhostBlack80 = Color(0xCC1E1E1E)
val GhostBlack20 = Color(0x331E1E1E)
val GhostWhite = Color(0xFFFAFAFA)
val RingColor = Color(0xCCAEB6BF)


val primaryLight = Color(0xFF702AE2)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEADDFF)
val onPrimaryContainerLight = Color(0xFF220F46)
val secondaryLight = Color(0xFF6D49A9)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE9DEF8)
val onSecondaryContainerLight = Color(0xFF1E182B)
val tertiaryLight = Color(0xFF7E525E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E1)
val onTertiaryContainerLight = Color(0xFF31101C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFEF7FF)
val onBackgroundLight = Color(0xFF1D1B20)
val surfaceLight = Color(0xFFFEF7FF)
val onSurfaceLight = Color(0xFF1D1B20)
val surfaceVariantLight = Color(0xFFE7E0EB)
val onSurfaceVariantLight = Color(0xFF49454E)
val outlineLight = Color(0xFFF5B041)
val outlineVariantLight = Color(0xFFCBC4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F35)
val inverseOnSurfaceLight = Color(0xFFF5EFF7)
val inversePrimaryLight = Color(0xFFD2BCFD)
val surfaceDimLight = Color(0xFFDED8E0)
val surfaceBrightLight = Color(0xFFFEF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F1FA)
val surfaceContainerLight = Color(0xFFF2ECF4)
val surfaceContainerHighLight = Color(0xFFECE6EE)
val surfaceContainerHighestLight = Color(0xFFE7E0E8)